export const presetNames = [
  "ava",
  "base",
  "browser",
  "disableTypeChecked",
  "ignores",
  "jsdoc",
  "json",
  "node",
  "packageJson",
  "recommended",
  "stylistic",
  "testingLibrary",
  "typeChecked",
  "typescript",
  "vitest",
] as const;
